D-B-8/created pet feature
DimaKabanov/PetFamily pull request #18
Opened 2024-09-26 02:37 UTC by DimaKabanov

2024-09-26 03:09 UTC, DimaKabanov commented on PetFamily.Backend/src/PetFamily.Domain/Models/Volunteers/Pets/ValueObjects/PhotoPath.cs
> +public record PhotoPath
Нужно ли этот value object делать общим? Сейчас получилось, что он заточен под фото, но могут появиться и другие файлы. Была мысль перетащить его в `/Shared/ValueObjects` и назвать `FilePath`

2024-09-26 03:12 UTC, DimaKabanov commented on PetFamily.Backend/src/PetFamily.Application/Volunteers/AddPet/AddPetService.cs
> +                .Select(path => new Photo(path, false))
фото у нас также содержит свойство IsMain. Не могу сообразить как правильно получить его? Фото в AddPetRequest мы получаем как IFormFileCollection, но как сопоставить с каждым файлом bool-флаг IsMain не пойму

2024-09-26 10:03 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Models/Volunteers/Pets/ValueObjects/PhotoPath.cs
> +public record PhotoPath
Можно, если что, в будущем можно будет сделать отдельный

2024-09-26 10:03 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Application/Volunteers/AddPet/AddPetService.cs
> +                .Select(path => new Photo(path, false))
Пользователь будет отдельным запросо устанавливать выбранное фото главным, там он уже будет отправлять путь к фото

2024-09-26 10:07 UTC, KirillSachkov requested changes
Всё хорошо, только нужно вынести создание фотографий в отдельный метод

2024-09-26 10:07 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.API/Contracts/AddPetRequest.cs
> +    IFormFileCollection Photos);
Фотографии нужно загружать отдельным endpoint, в задании это указано
![image](https://github.com/user-attachments/assets/8a23966f-cad3-430c-bc40-0c6a6126065a)

2024-09-27 08:25 UTC, KirillSachkov approved these changes

2024-09-27 08:55 UTC, merged